env: standard
runtime: nodejs16
default_expiration: "12h"
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95

  max_idle_instances: 1
  min_instances: 0
network:
  session_affinity: true
