env: standard
runtime: nodejs16
instance_class: F4
default_expiration: "12h"
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_instances: 2
